AssignmentSubmission/Controllers/AuthController.cs
using AssignmentSubmission.BAL.Models;
using AssignmentSubmission.DAL.Models;
using AssignmentSubmission.DAL.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Json;
using System.Text.Json.Serialization;
using AssignmentSubmission.BAL.Constants;

namespace AssignmentSubmission.Controllers
{
    public class AuthController : Controller
    {
        private readonly ILogger<AuthController> _logger;
        private readonly IMainDBUnitOfWork _IMainDBUnitOfWork;

        public AuthController(
            ILogger<AuthController> logger,
            IMainDBUnitOfWork mainDBUnitOfWork
            )
        {
            _logger = logger;
            _IMainDBUnitOfWork = mainDBUnitOfWork;
        }

        [HttpGet]
        public IActionResult Login()
        {
            HttpContext.Session.SetString("User", "The Doctor");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            var res = (await _IMainDBUnitOfWork.UserDetailsRepository.GetAllAsync()).Where(x => x.Email == loginModel.Email && x.Password == loginModel.Password && x.Status == Status.Active).FirstOrDefault();
            if (res != null)
            {
                ActiveUserModel activeUserModel = new ActiveUserModel
                {
                    Email = res.Email,
                    FirstName = res.FirstName,
                    LastName = res.LastName,
                    Role = res.Role,
                    Id = res.UserId,
                    Phone = res.Phone,
                    Gender = res.Gender
                };
                string userdata = JsonSerializer.Serialize(activeUserModel);
                HttpContext.Session.SetString("ActiveUser", userdata);
            }
            return View();
        }
        [HttpGet]
        public IActionResult Registration()
        {
            var data = HttpContext.Session.GetString("User");
            ResponseModel response = new ResponseModel
            {
                Success = true,
                Message = $"Registre Here.."
            };
            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Registration(RegistrationModel registrationModel)
        {
            ResponseModel response = new ResponseModel();
            var ExistUser = (await _IMainDBUnitOfWork.UserDetailsRepository.GetAllAsync()).Where(x => x.Email == registrationModel.Email).FirstOrDefault();
            if (ExistUser == null)
            {
                UserDetails user = new UserDetails
                {
                    DateOfCreated = DateTime.Now,
                    DateOfModify = DateTime.Now,
                    Email = registrationModel.Email,
                    FirstName = registrationModel.FirstName,
                    LastName = registrationModel.LastName,
                    Gender = registrationModel.Gender,
                    Password = registrationModel.Password,
                    Phone = registrationModel.Phone,
                    Role = Role.User,
                    Status = Status.Active
                };
                _IMainDBUnitOfWork.UserDetailsRepository.Insert(user);
                var res = await _IMainDBUnitOfWork.SaveAsync();
                if (res > 0)
                {
                    response = new ResponseModel
                    {
                        Success = true,
                        Message = $"User saved successfully"
                    };
                    return View(response);
                }
                else
                {
                    response = new ResponseModel
                    {
                        Success = false,
                        Message = $"Failed to create user"
                    };
                    return View(response);
                }
            }
            else
            {
                response = new ResponseModel
                {
                    Success = false,
                    Message = $"User with email : {registrationModel.Email} allready exist"
                };
            }
            return View(response);
        }
        public IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult UserProfile()
        {
            StudentModel studentModel = new StudentModel();
            var x = HttpContext.Session.GetString("ActiveUser");
            if (x != null)
            {
                ActiveUserModel userData = new ActiveUserModel();
                userData = JsonSerializer.Deserialize<ActiveUserModel>(x);
                if (!string.IsNullOrEmpty(userData.Email))
                {
                    studentModel.Email = userData.Email;
                    studentModel.FirstName = userData.FirstName;
                    studentModel.LastName = userData.LastName;
                    studentModel.Phone = userData.Phone;
                    studentModel.Role = userData.Role;
                    studentModel.Gender = userData.Gender;
                    studentModel.UserId = userData.Id;

                }
                var studentProfile = _IMainDBUnitOfWork.StudentDetailsRepository.GetAll().
                    Where(x => x.UserId == userData.Id).FirstOrDefault();
                if (studentProfile != null)
                {
                    studentModel.Id = studentProfile.StudentId;
                    studentModel.ProgramDetailsId = studentProfile.StudentProgramId;
                    studentModel.Status = studentProfile.Status;
                    studentModel.UserId = studentProfile.UserId;
                    studentModel.DOB = studentProfile.DOB;
                    studentModel.StudyCenterCode = studentProfile.StudyCenterCode;
                    studentModel.EnrollmentNo = studentProfile.EnrollmentNo;
                }
            }
            return View(studentModel);
        }
        [HttpPost]
        public IActionResult UserProfile(StudentModel studentModel)
        {
            if (studentModel.UserId != 0 && !string.IsNullOrEmpty(studentModel.Email))
            {
                var result = _IMainDBUnitOfWork.StudentDetailsRepository.GetAll().Where(x => x.UserId == studentModel.UserId).FirstOrDefault();
                StudentDetails studentDetails = new StudentDetails();
                // studentDetails.ProgramDetails = _IMainDBUnitOfWork.ProgramsDetailsRepository.GetById(studentModel.ProgramDetailsId);
                studentDetails.Status = Status.Active;
                studentDetails.StudyCenterCode = studentModel.StudyCenterCode;
                studentDetails.EnrollmentNo = studentModel.EnrollmentNo;
                studentDetails.StudentProgramId = 2;
                studentDetails.DOB = studentModel.DOB;
                studentDetails.DateOfCreated = DateTime.Now;
                studentDetails.DateOfModify = DateTime.Now;
                if (result != null)
                {

                    studentDetails.StudentId = result.StudentId;
                    _IMainDBUnitOfWork.StudentDetailsRepository.Update(studentDetails);
                    _IMainDBUnitOfWork.Save();
                }
                else
                {
                    studentDetails.UserId = studentModel.UserId;
                    _IMainDBUnitOfWork.StudentDetailsRepository.Insert(studentDetails);
                    _IMainDBUnitOfWork.Save();
                }
            }
            return RedirectToAction("UserProfile");
        }
        [HttpGet]
        public IActionResult ResetPassword()
        {
            ResponseModel responseModel = new ResponseModel
            {
                data = null,
                Message = ""
            };
            return View(responseModel);
        }
        [HttpPost]
        public IActionResult ResetPassword(PasswordResetModel passwordResetModel)
        {
            ResponseModel responseModel = new ResponseModel();
            var x = HttpContext.Session.GetString("ActiveUser");
            if (x != null)
            {
                ActiveUserModel userData = new ActiveUserModel();
                userData = JsonSerializer.Deserialize<ActiveUserModel>(x);
                UserDetails user = _IMainDBUnitOfWork.UserDetailsRepository.GetAll().Where
                    (x => x.Email == userData.Email && x.Password == passwordResetModel.OldPassword).FirstOrDefault();
                if (user != null)
                {
                    user.Password = passwordResetModel.NewPassword;
                    _IMainDBUnitOfWork.UserDetailsRepository.Update(user);
                    _IMainDBUnitOfWork.Save();
                    responseModel.data = null;
                    responseModel.Message = "Password Changed";
                }
            }
            return View(responseModel);
        }

        [HttpGet]
        public IActionResult ForgetPassword()
        {
            ResponseModel responseModel = new ResponseModel();
            return View(responseModel);
        }
        [HttpPost]
        public IActionResult ForgetPassword(PasswordResetModel PRM)
        {
            ResponseModel responseModel = new ResponseModel();
            var user=_IMainDBUnitOfWork.UserDetailsRepository.GetAll().Where(x => 
            x.Email == PRM.Email && x.Phone == PRM.Phone).FirstOrDefault();
            if (user!=null)
            {
                user.Password = PRM.NewPassword;
                _IMainDBUnitOfWork.UserDetailsRepository.Update(user);
                _IMainDBUnitOfWork.Save();

                responseModel.Message = "Password Reset Sussfully..";
            }
            else
            {

AssignmentSubmission/Controllers/MasterController.cs
using AssignmentSubmission.BAL.Models;
using AssignmentSubmission.DAL.Models;
using AssignmentSubmission.DAL.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using AssignmentSubmission.BAL.Constants;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AssignmentSubmission.BAL.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using AssignmentSubmission.Models;

namespace AssignmentSubmission.Controllers
{
    public class MasterController : Controller
    {
        private readonly ILogger<MasterController> _logger;
        private readonly IMainDBUnitOfWork _IMainDBUnitOfWork;
        private readonly MasterService _masterService;
        private readonly TeacherService _teacherService;
        public MasterController(
            ILogger<MasterController> logger,
            IMainDBUnitOfWork mainDBUnitOfWork,
            MasterService masterService,
            TeacherService teacherService
            ) 
        {
            _logger = logger;
            _IMainDBUnitOfWork = mainDBUnitOfWork;
            _masterService = masterService;
            _teacherService = teacherService;
        }
        #region Manage Program
        public async Task<IActionResult> GetAllProgram()
        {
            ResponseModel courses = await _masterService.GetAllPrograms();

            return View(courses);
        }
        [HttpGet]
        public IActionResult AddProgram(int Id = 0)
        {
            ProgramModel programModel = new ProgramModel();
            if (Id != 0)
            {
                var result = _IMainDBUnitOfWork.ProgramsDetailsRepository.GetById(Id);
                if (result != null)
                {
                    programModel.Id = result.ProgramId;
                    programModel.ProgramName = result.Title;
                    programModel.ProgramCode = result.Code;

                    return View(programModel);
                }
            }
            return View(programModel);
        }
        [HttpPost]
        public IActionResult AddProgram(ProgramModel programModel)
        {
            if (programModel.Id != 0)
            {
                ProgramsDetails program = new ProgramsDetails()
                {
                    ProgramId = programModel.Id,
                    Code = programModel.ProgramCode,
                    Title = programModel.ProgramName,
                    DateOfModify = DateTime.Now,
                };
                _IMainDBUnitOfWork.ProgramsDetailsRepository.Update(program);
                _IMainDBUnitOfWork.Save();
            }
            else
            {
                ProgramsDetails program = new ProgramsDetails()
                {
                    Code = programModel.ProgramCode,
                    Title = programModel.ProgramName,
                    DateOfModify = DateTime.Now,
                    DateOfCreated = DateTime.Now,
                    Status = Status.Active
                };
                _IMainDBUnitOfWork.ProgramsDetailsRepository.Insert(program);
                _IMainDBUnitOfWork.Save();
            }
            return RedirectToAction("GetAllProgram");
        }
        public IActionResult EditProgram(int Id)
        {
            return RedirectToAction("AddProgram", new { Id = Id });
        }
        public IActionResult DeleteProgram(int Id)
        {
            var program = _IMainDBUnitOfWork.ProgramsDetailsRepository.GetById(Id);
            _IMainDBUnitOfWork.ProgramsDetailsRepository.Delete(program);
            _IMainDBUnitOfWork.Save();
            return RedirectToAction("GetAllProgram");
        }

        #endregion
        #region Manage Course
        public async Task<IActionResult> GetAllCourses()
        {
            var courses = await _masterService.GetAllCourse();
            if (courses != null)
            {
                ResponseModel responseModel = new ResponseModel()
                {
                    data = courses,
                    Message = "",
                    Success = true
                };
                return View(responseModel);
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddCourse(int Id = 0)
        {
            DropDownModel dropDown = new DropDownModel();
            var programs = await _masterService.GetAllPrograms();
            SelectList selectLists;
            if (programs != null && programs.Success && Id == 0)
            {
                selectLists = new SelectList((List<ProgramModel>)programs.data, "Id", "ProgramName");
                dropDown.DropDownData = selectLists;
            }
            if (Id != 0)
            {
                var data = _IMainDBUnitOfWork.CourseDetailsRepository.GetById(Id);
                CourseModel courseModel = new CourseModel()
                {
                    Id = data.CourseId,
                    Code = data.Coursecode,
                    ProgramId = data.ProgramId,
                    Title = data.Title
                };
                var defaultValue = ((List<ProgramModel>)programs.data).Where(x => x.Id == data.ProgramId).FirstOrDefault();
                selectLists = new SelectList((List<ProgramModel>)programs.data, "Id", "ProgramName", defaultValue);
                dropDown.DropDownData = selectLists;
                dropDown.Data = courseModel;
            }
            return View(dropDown);
        }

        [HttpPost]
        public IActionResult AddCourse(CourseModel courseModel)
        {
            if (courseModel.Id > 0)
            {
                CourseDetails course = new CourseDetails()
                {
                    CourseId = courseModel.Id,
                    ProgramId = courseModel.ProgramId,
                    Coursecode = courseModel.Code,
                    Title = courseModel.Title,
                    DateOfModify = DateTime.Now
                };
                _IMainDBUnitOfWork.CourseDetailsRepository.Update(course);
                _IMainDBUnitOfWork.Save();
            }
            else
            {

                CourseDetails course = new CourseDetails()
                {
                    ProgramId = courseModel.ProgramId,
                    Coursecode = courseModel.Code,
                    Title = courseModel.Title,
                    DateOfModify = DateTime.Now,
                    DateOfCreated = DateTime.Now,
                    Status = Status.Active
                };
                _IMainDBUnitOfWork.CourseDetailsRepository.Insert(course);
                _IMainDBUnitOfWork.Save();
            }
            return RedirectToAction("GetAllCourses");
        }

        public IActionResult EditCourse(int Id)
        {
            return RedirectToAction("AddCourse", new { Id = Id });
        }
        public IActionResult DeleteCourse(int Id)
        {
            var course = _IMainDBUnitOfWork.CourseDetailsRepository.GetById(Id);
            _IMainDBUnitOfWork.CourseDetailsRepository.Delete(course);
            _IMainDBUnitOfWork.Save();
            return RedirectToAction("GetAllCourses");
        }
        #endregion
        [HttpGet]
        public IActionResult GetAllTeacher()
        {
            return View();
        }

        [HttpGet]
        public IActionResult AddTeacher()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddTeacher(TeacherModel teacherModel)
        {
            _teacherService.AddTeacher(teacherModel);
            return View();
        }

    }
}

AssignmentSubmission/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using AssignmentSubmission.BAL.Constants
@using System.Text.Json
@{
    var x = Context.Session.GetString("ActiveUser");
    ActiveUserModel userData = new ActiveUserModel();
    if (x != null)
    {
        userData = JsonSerializer.Deserialize<ActiveUserModel>(x);
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AssignmentSubmission</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@


    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AssignmentSubmission</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (string.IsNullOrEmpty(userData.Email))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Registration">Registration</a>
                            </li>
                        }
                        else
                        {

                            @if (userData.Role == Role.Admin)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Master" asp-action="GetAllProgram">Manage Program</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Master" asp-action="GetAllCourses">Manage Course</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Master" asp-action="GetAllTeacher">Manage Teachers</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-area="" asp-controller="Assignment" asp-action="UploadAssignment">Upload Assignment</a>
                                </li>
                            }
                        }


                    </ul>

                    <ul id="ddlprofile" class="navbar-nav" style="float: right;">
                        @if (!string.IsNullOrEmpty(userData.Email))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-user-circle fa-2x"></i>
                                </a>

                                <div class="dropdown-menu " x-placement="bottom-start"
                                     style="position: absolute;will-change: transform;top: auto;left: -117px;"
                                     aria-labelledby="navbarDropdown">
                                    <h6 align="center" id="ddlloginName"></h6>
                                    <h6 align="center" id="ddlloginemail"></h6>

                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="UserProfile"><i class="fa fa-user"> Profile</i></a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="ResetPassword"><i class="fa fa-cog"> Change Password</i></a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="LogOut"><i class="fa fa-lock"> Logout</i></a>
                                      
                                </div>
                            </li>
                        }
                    </ul>
                </div>
            </div>

            <div>
                @if (!string.IsNullOrEmpty(userData.Email))
                {
                    <h6 class="text-white">Welcome: @userData.FirstName</h6>
                }
            </div>
        </nav>
    </header>
    <div class="container" style="min-height:450px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-primary footer text-white font-small special-color-dark pt-4">
       
            <div class="container">

                <!-- Social buttons -->
                <ul class="list-unstyled list-inline text-center">
                    <li class="list-inline-item">
                        <a class="btn-floating btn-fb mx-1">
                            <i class="fab fa-facebook-f fa-2x"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-tw mx-1">
                            <i class="fab fa-twitter fa-2x"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-gplus mx-1">
                            <i class="fab fa-google-plus-g fa-2x"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-li mx-1">
                            <i class="fab fa-linkedin-in fa-2x"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-dribbble mx-1">
                            <i class="fab fa-dribbble fa-2x"> </i>
                        </a>
                    </li>
                </ul>
                <!-- Social buttons -->

            </div>
            <!-- Footer Elements -->
            <!-- Copyright -->
            <div class="footer-copyright  bg-info text-center py-3">
                <a href="#" class="btn text-white text-capitalize">System for Managing Online Submission of Assignment</a>
                <p>Developed  By Vikram</p>
            </div>
            <!-- Copyright -->
        </footer>
        @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        @RenderSection("Scripts", required: false)
</body>
</html>